GET http://localhost:3001/api/blogs/

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title": "wg",
    "url":"localhost",
    "author":"aziz_li"
}

###
DELETE http://localhost:3001/api/blogs/

###
PUT http://localhost:3001/api/blogs/62cc8f9edec8c1278f57dd5d
Content-Type: application/json

{
    "likes":10
}
