### ADD USER
POST  http://localhost:3001/api/users/
Content-Type: application/json

{
    "name":"abdulaziz",
    "password":"password",
    "username":"certy_freak"
}

### LOGIN 
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"certy_freak",
    "password":"password"
}

### GET USERS
GET  http://localhost:3001/api/users/